#!/bin/sh

# require build-essential, git

SCRIPT=$(readlink -f $0)
CWD=$(dirname $SCRIPT)
FILES=$CWD/files

replace_file() {
  src=$FILES/$1
  dst=$HOME/.$1
  if [ -f $dst -o -d $dst ]; then
    echo "$dst exists: [s]kip, [o]verwrite, [b]ackup ?"
    read rep
    case "$rep" in
      b|B)
        mv $dst ${dst}.old
        ln -s $src $dst
        ;;
      o|O)
        rm -rf $dst
        ln -s $src $dst
        ;;
      *)
        echo "Skipping $dst"
        ;;
    esac
  else
    ln -s $src $dst
  fi
}

setup_files() {
  for file in $(ls $FILES); do
    orifile=$FILES/$file
    dotfile=$HOME/.$file
    if [ -L $dotfile ]; then
      absfile=$(readlink -f $dotfile)
      if [ $absfile != $orifile ]; then
        echo $dotfile links to $absfile
        replace_file $file
      fi
    else
      replace_file $file
    fi
  done
}

setup_vim() {
  echo "Setting up Vim"
  PLUGIN_DIR=$FILES/vim/bundle
  mkdir -p $PLUGIN_DIR
  for plugin in vim_plugins/*; do
    plugin_name=$(basename $plugin)
    if [ ! -d $PLUGIN_DIR/$plugin_name ]; then
      echo " * Installing $plugin_name"
      cd $PLUGIN_DIR; git clone $(cat $CWD/$plugin) $plugin_name 2> /dev/null; cd $OLDPWD
    else
      echo " * Updating $plugin_name"
      cd $PLUGIN_DIR/$plugin_name; git pull > /dev/null; cd $OLDPWD
    fi
  done
}

setup_rbenv() {
  RBENV=$HOME/.rbenv
  PLUGINS=$RBENV/plugins

  if [ ! -d $RBENV ]; then
    git clone https://github.com/sstephenson/rbenv.git $RBENV
    mkdir -p $PLUGINS
    git clone https://github.com/sstephenson/ruby-build.git $PLUGINS/ruby-build
    git clone https://github.com/jf/rbenv-gemset.git $PLUGINS/rbenv-gemset
    git clone git://github.com/dcarley/rbenv-sudo.git $PLUGINS/rbenv-sudo

    PATH=$RBENV/bin:$PATH
    eval "$(rbenv init -)"

    rbenv install -l
    echo -n "Ruby version: "
    read ruby
    rbenv install $ruby
    rbenv rehash
    rbenv global $ruby

    for gemset in $(ls $CWD/gemsets); do
      rbenv gemset create $ruby $gemset
      echo $gemset > $HOME/.rbenv-gemsets
      gem install bundler
      rbenv rehash
      bundle install --gemfile $CWD/gemsets/$gemset
      rbenv rehash
    done
  fi
}

setup_files
setup_vim
setup_rbenv
