#!/bin/sh

# require build-essential, git

SCRIPT=$(readlink -f $0)
CWD=$(dirname $SCRIPT)
FILES=$CWD/files
DEFAULT_RUBY=2.1.0

[ -z $RUBY ] && RUBY=$DEFAULT_RUBY

replace_file() {
  src=$FILES/$1
  dst=$HOME/.$1
  if [ -f $dst -o -d $dst ]; then
    echo "$dst exists: [s]kip, [o]verwrite, [b]ackup ?"
    read rep
    case "$rep" in
      b|B) mv $dst ${dst}.old; ln -s $src $dst ;;
      o|O) rm -rf $dst; ln -s $src $dst ;;
      *) echo "Skipping $dst" ;;
    esac
  else
    ln -s $src $dst
  fi
}

setup_files() {
  echo "Setting up .dotfiles"
  for file in $(ls $FILES); do
    orifile=$FILES/$file
    dotfile=$HOME/.$file
    if [ -L $dotfile ]; then
      absfile=$(readlink -f $dotfile)
      if [ $absfile != $orifile ]; then
        echo $dotfile links to $absfile
        replace_file $file
      fi
    else
      replace_file $file
    fi
  done
}

setup_vim() {
  echo "Setting up Vim"
  PLUGIN_DIR=$FILES/vim/bundle
  mkdir -p $PLUGIN_DIR
  for plugin in vim_plugins/*; do
    plugin_name=$(basename $plugin)
    if [ ! -d $PLUGIN_DIR/$plugin_name ]; then
      echo " * Installing $plugin_name"
      cd $PLUGIN_DIR; git clone $(cat $CWD/$plugin) $plugin_name 2> /dev/null; cd $OLDPWD
    else
      echo " * Updating $plugin_name"
      cd $PLUGIN_DIR/$plugin_name; git pull > /dev/null; cd $OLDPWD
    fi
  done
}

setup_rbenv() {
  echo "Setting up rbenv"
  RBENV=$HOME/.rbenv
  PLUGIN_DIR=$RBENV/plugins

  if [ ! -d $RBENV ]; then
    echo " * Installing rbenv"
    git clone https://github.com/sstephenson/rbenv.git $RBENV 2> /dev/null

    fresh=1
  else
    echo " * Updating rbenv"
    cd $RBENV; git pull > /dev/null; cd $OLDPWD

    fresh=0
  fi

  mkdir -p $PLUGIN_DIR
  for plugin in rbenv_plugins/*; do
    plugin_name=$(basename $plugin)
    if [ ! -d $PLUGIN_DIR/$plugin_name ]; then
      echo " * Installing $plugin_name"
      cd $PLUGIN_DIR; git clone $(cat $CWD/$plugin) $plugin_name 2> /dev/null; cd $OLDPWD
    else
      echo " * Updating $plugin_name"
      cd $PLUGIN_DIR/$plugin_name; git pull > /dev/null; cd $OLDPWD
    fi
  done

  [ $fresh -eq 1 ] && install_ruby
}

install_ruby() {
  echo "Installing ruby $RUBY"
  PATH=$HOME/.rbenv/bin:$PATH
  eval "$(rbenv init -)"
  rbenv install $RUBY
  rbenv rehash
  rbenv global $RUBY

  for gemset in $(ls $CWD/gemsets); do
    rbenv gemset create $ruby $gemset
    echo $gemset > $HOME/.rbenv-gemsets
    gem install bundler
    rbenv rehash
    bundle install --gemfile $CWD/gemsets/$gemset
    rbenv rehash
  done
}

setup_files
setup_vim
setup_rbenv
