set rtp+=~/.vim/bundle/vundle/
call vundle#rc()

Bundle 'gmarik/vundle'

let mapleader = ","
let localleader = ","

set nocompatible

syntax on
filetype plugin indent on
set encoding=utf-8
set fileencoding=utf-8

set t_Co=256
set background=dark
colorscheme desert256

set autoindent
set smartindent
set tabstop=2
set expandtab
set softtabstop=2
set shiftwidth=2
set shiftround

set nobackup
set nowritebackup
set noswapfile

set ruler
set laststatus=2
set title
set backspace=indent,eol,start
set history=10000
set showmatch
set showcmd
set showmode
set incsearch
set cursorline

"set foldmethod=indent
"set foldnestmax=10
"set foldlevel=1

set wildmenu
set wildmode=list:longest,full

set pastetoggle=<F2>
nnoremap <F2> :set invpaste paste?<CR>

set list listchars=tab:»·,trail:·
highlight SpecialKey ctermfg=red ctermbg=red

autocmd BufWritePre <buffer> :call setline(1,map(getline(1,"$"),'substitute(v:val,"\\s\\+$","","")'))
autocmd BufNewFile,BufReadPost *.json setlocal filetype=javascript.json

" Ctrl-C > copy to clip
vmap <C-c> y: call system("xclip -i -selection clipboard", getreg("\""))<CR>

noremap <C-j> <C-w>j
noremap <C-k> <C-w>k
noremap <C-l> <C-w>l
noremap <C-h> <C-w>h
nnoremap Y y$
nnoremap <leader>d ddO
nnoremap - ddkP
nnoremap _ ddp

" Plugin settings

Bundle 'Raimondi/delimitMate'
Bundle 'bling/vim-airline'
Bundle 'tpope/vim-endwise'
Bundle 'elzr/vim-json'

Bundle 'kien/ctrlp.vim'
nnoremap <leader>h :CtrlP<CR>
let g:ctrlp_working_path_mode = 'rc'

Bundle 'scrooloose/nerdtree'
Bundle 'Xuyuanp/nerdtree-git-plugin'
nnoremap <leader>n :NERDTreeToggle<CR>
let NERDTreeHighlightCursorline=1
let NERDTreeIgnore = ['tmp', 'pkg']
autocmd VimEnter * if argc() == 0 | NERDTree | endif
autocmd bufenter * if (winnr("$") == 1 && exists("b:NERDTreeType") && b:NERDTreeType == "primary") | q | endif

Bundle 'krisajenkins/vim-pipe'
let g:vimpipe_invoke_map = '<leader>r'
let g:vimpipe_close_map = '<leader>p'

Bundle 'kien/rainbow_parentheses.vim'
au VimEnter * RainbowParenthesesToggle
au Syntax * RainbowParenthesesLoadRound
au Syntax * RainbowParenthesesLoadSquare
au Syntax * RainbowParenthesesLoadBraces
