# zsh config entry point

ZSH=$HOME/.zsh

BASE_PATH=/usr/local/bin:/usr/local/sbin:/usr/bin:/usr/sbin:/bin:/sbin
export PATH=$HOME/.go/bin:$HOME/bin:$BASE_PATH

export TEXPATH=~/.tex
export TEXINPUTS=$TEXINPUTS:$TEXPATH

export VISUAL=view
export EDITOR=vim

# Set to this to use case-sensitive completion
# CASE_SENSITIVE="true"
# Uncomment following line if you want red dots to be displayed while waiting for completion
# COMPLETION_WAITING_DOTS="true"

fpath=($ZSH/plugins $fpath)

autoload -U compinit
compinit -i

for config_file ($ZSH/lib/*.zsh); do
  source $config_file
done

for extra_file ($ZSH/extra/*.zsh); do
  source $extra_file
done

source $ZSH/prompt

gpg-connect-agent /bye
load_ssh_keys
