[[ $- != *i*  ]] && return
if [[ $TERM != screen*  ]]; then
  session=$(tmux list-sessions | awk -F':' '/[^\(attached\)]$/ {print $1}' | head -1)
  if [ "x$session" != "x" ]; then
    exec tmux attach -t $session
  else
    exec tmux
  fi
fi

ZSH=$HOME/.zsh

BASE_PATH=/usr/local/bin:/usr/local/sbin:/usr/bin:/usr/sbin:/bin:/sbin
export PATH=$HOME/bin:$BASE_PATH

export TEXPATH=~/.tex
export TEXINPUTS=$TEXINPUTS:$TEXPATH

export VISUAL=view
export EDITOR=vim

# Set to this to use case-sensitive completion
# CASE_SENSITIVE="true"
# Uncomment following line if you want red dots to be displayed while waiting for completion
# COMPLETION_WAITING_DOTS="true"

fpath=($ZSH/plugins $fpath)

autoload -U compinit
compinit -i

for config_file ($ZSH/lib/*.zsh); do
  source $config_file
done

for extra_file ($ZSH/extra/*.zsh); do
  source $extra_file
done

source $ZSH/prompt

setup_gpg_agent
load_ssh_keys
